In [1]:
import os
os.chdir(r'D:\pyc\Countries')

In [2]:
import pandas as pd

In [8]:
df = pd.read_csv('annual-enterprise-survey-2021-financial-year-provisional-csv.csv')

In [9]:
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
41710,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41711,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41712,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41713,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41714,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [10]:
df.shape

(41715, 10)

In [11]:
df.describe

<bound method NDFrame.describe of        Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2021                     Level 1                99999
1      2021                     Level 1                99999
2      2021                     Level 1                99999
3      2021                     Level 1                99999
4      2021                     Level 1                99999
...     ...                         ...                  ...
41710  2013                     Level 3                 ZZ11
41711  2013                     Level 3                 ZZ11
41712  2013                     Level 3                 ZZ11
41713  2013                     Level 3                 ZZ11
41714  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
41710  Food product manufacturing          Percentage           H37
41711  Food product manufacturing          Percentage           H38
41712  Food product manufacturing          Percentage           H39
41713  Food product manufacturing          Percentage           H40
41714  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
41710                                      Quick ratio       Financial ratios
41711              Margin on sales of goods for resale       Financial ratios
41712                                 Return on equity       Financial ratios
41713                           Return on total assets       Financial ratios
41714                            Liabilities structure       Financial ratios

         Value                             Industry_code_ANZSIC06
0      757,504  ANZSIC06 divisions A-S (excluding classes K633...
1      674,890  ANZSIC06 divisions A-S (excluding classes K633...
2       49,593  ANZSIC06 divisions A-S (excluding classes K633...
3       33,020  ANZSIC06 divisions A-S (excluding classes K633...
4      654,404  ANZSIC06 divisions A-S (excluding classes K633...
...        ...                                                ...
41710       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
41711       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
41712       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
41713        5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
41714       46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[41715 rows x 10 columns]>

In [12]:
df.describe()

              Year
count  41715.00000
mean    2017.00000
std        2.58202
min     2013.00000
25%     2015.00000
50%     2017.00000
75%     2019.00000
max     2021.00000

In [13]:
df.values

array([[2021, 'Level 1', '99999', ..., 'Financial performance',
        '757,504',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', '99999', ..., 'Financial performance',
        '674,890',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', '99999', ..., 'Financial performance', '49,593',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       ...,
       [2013, 'Level 3', 'ZZ11', ..., 'Financial ratios', '12',
        'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'],
       [2013, 'Level 3', 'ZZ11', ..., 'Financial ratios', '5',
        'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'],
       [2013, 'Level 3', 'ZZ11', ..., 'Financial ratios', '46',
        'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119']],
      dtype=object)

In [14]:
X = df.drop(columns=['Industry_code_ANZSIC06'])

In [15]:
X

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504"
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890"
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593"
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020"
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404"
...,...,...,...,...,...,...,...,...,...
41710,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52
41711,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40
41712,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12
41713,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5
41714,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46

In [18]:
Y = df['Year']
Y

0        2021
1        2021
2        2021
3        2021
4        2021
         ...
41710    2013
41711    2013
41712    2013
41713    2013
41714    2013
Name: Year, Length: 41715, dtype: int64

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
model = DecisionTreeClassifier()
model.fit(X, Y)

ValueError: could not convert string to float: 'Level 1'

In [21]:
Z = df['Value']
Z

0        757,504
1        674,890
2         49,593
3         33,020
4        654,404
          ...
41710         52
41711         40
41712         12
41713          5
41714         46
Name: Value, Length: 41715, dtype: object

In [23]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(Y, Z)

ValueError: Expected 2D array, got 1D array instead:
array=[2021. 2021. 2021. ... 2013. 2013. 2013.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41715 entries, 0 to 41714
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         41715 non-null  int64
 1   Industry_aggregation_NZSIOC  41715 non-null  object
 2   Industry_code_NZSIOC         41715 non-null  object
 3   Industry_name_NZSIOC         41715 non-null  object
 4   Units                        41715 non-null  object
 5   Variable_code                41715 non-null  object
 6   Variable_name                41715 non-null  object
 7   Variable_category            41715 non-null  object
 8   Value                        41715 non-null  object
 9   Industry_code_ANZSIC06       41715 non-null  object
dtypes: int64(1), object(9)
memory usage: 3.2+ MB

In [25]:
df['Units']

0        Dollars (millions)
1        Dollars (millions)
2        Dollars (millions)
3        Dollars (millions)
4        Dollars (millions)
                ...
41710            Percentage
41711            Percentage
41712            Percentage
41713            Percentage
41714            Percentage
Name: Units, Length: 41715, dtype: object

In [26]:
df.iloc[3000]

Year                                                               2021
Industry_aggregation_NZSIOC                                     Level 1
Industry_code_NZSIOC                                                 JJ
Industry_name_NZSIOC           Information Media and Telecommunications
Units                                                Dollars (millions)
Variable_code                                                       H21
Variable_name                                            Opening stocks
Variable_category                                 Financial performance
Value                                                               325
Industry_code_ANZSIC06                              ANZSIC06 division J
Name: 3000, dtype: object

In [27]:
df.Variable_category

0        Financial performance
1        Financial performance
2        Financial performance
3        Financial performance
4        Financial performance
                 ...
41710         Financial ratios
41711         Financial ratios
41712         Financial ratios
41713         Financial ratios
41714         Financial ratios
Name: Variable_category, Length: 41715, dtype: object

In [28]:
df.Variable_category == 'Financial performance'

0         True
1         True
2         True
3         True
4         True
         ...
41710    False
41711    False
41712    False
41713    False
41714    False
Name: Variable_category, Length: 41715, dtype: bool

In [37]:
df2 = df[df.Variable_category == 'Financial performance']

In [32]:
df2.to_csv('Financial performance.csv')

In [33]:
df.Industry_name_NZSIOC

0                    All industries
1                    All industries
2                    All industries
3                    All industries
4                    All industries
                    ...
41710    Food product manufacturing
41711    Food product manufacturing
41712    Food product manufacturing
41713    Food product manufacturing
41714    Food product manufacturing
Name: Industry_name_NZSIOC, Length: 41715, dtype: object

In [38]:
df2

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
41692,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H18,Other purchases and operating expenses,Financial performance,"28,496","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41693,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H20,Non-operating expenses,Financial performance,93,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41694,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H21,Opening stocks,Financial performance,"3,722","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41695,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H22,Closing stocks,Financial performance,"4,041","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41696,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H23,Surplus before income tax,Financial performance,"1,227","ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [40]:
df.iloc[1:456]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
451,2021,Level 1,BB,Mining,Dollars,H34,Total income per employee count,Financial ratios,"886,300",ANZSIC06 division B
452,2021,Level 1,BB,Mining,Dollars,H35,Surplus per employee count,Financial ratios,"54,900",ANZSIC06 division B
453,2021,Level 1,BB,Mining,Percentage,H36,Current ratio,Financial ratios,105,ANZSIC06 division B
454,2021,Level 1,BB,Mining,Percentage,H37,Quick ratio,Financial ratios,95,ANZSIC06 division B
455,2021,Level 1,BB,Mining,Percentage,H39,Return on equity,Financial ratios,10,ANZSIC06 division B

In [41]:
df.Industry_aggregation_NZSIOC

0        Level 1
1        Level 1
2        Level 1
3        Level 1
4        Level 1
          ...
41710    Level 3
41711    Level 3
41712    Level 3
41713    Level 3
41714    Level 3
Name: Industry_aggregation_NZSIOC, Length: 41715, dtype: object

In [42]:
df.Industry_aggregation_NZSIOC == 'Level 1'

0         True
1         True
2         True
3         True
4         True
         ...
41710    False
41711    False
41712    False
41713    False
41714    False
Name: Industry_aggregation_NZSIOC, Length: 41715, dtype: bool

In [45]:
df3 = df[df.Industry_name_NZSIOC == 'Agriculture, Forestry and Fishing']

In [47]:
df3.to_csv('Agriculture, Forestry and Fishing.csv',index = False)

In [48]:
X = df.drop(columns=['Industry_code_ANZSIC06'])
X

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504"
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890"
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593"
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020"
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404"
...,...,...,...,...,...,...,...,...,...
41710,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52
41711,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40
41712,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12
41713,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5
41714,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46

TypeError: 'DataFrame' object is not callable

In [53]:
df.Value <= '20000'

0        False
1        False
2        False
3        False
4        False
         ...
41710    False
41711    False
41712     True
41713    False
41714    False
Name: Value, Length: 41715, dtype: bool

In [56]:
df[df.Value >= '20000']

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
41709,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H36,Current ratio,Financial ratios,91,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41710,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41711,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41713,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41714,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."